### ISSUE TITLE
Completly disable chat

### ISSUE THREAD

**Issue by mueller-ma** [mlsoft/Trycorder5#6]
How can I do that?

**Comment by mlsoft** [comment]
You go to setup at top right of the trycorder
change the autoboot for off
change the autostop for on

when you exit the trycorder, all communications are off

**Comment by mueller-ma** [comment]
Done, but when I start the app I get a "Trycorder Service started"

**Comment by mlsoft** [comment]
yes, only when the trycorder is active.
to disable network when active, go to communication/intercomm/srv-off
this will deactivate the net server
for this time only

**Comment by mueller-ma** [comment]
Can you add a possibility to disable it always?

**Comment by mlsoft** [comment]
Yes I can, this would make it a Trycorder without communication with the starship or any other trycorders.

This would make it a century old type of measuring device. Like the one Spock used with big buttons and a flap open to see your datas.

In fact it would make it a trycorder-1 version (which you can grab from xda in the historic versions)

To be precise you should download the 3.1 version from the XDA database. It will be limited in the way you would like. no server, no starship, no talk from anywhere.

From version 3.141592, the trycorder communicates with the starship it is assigned to.

The starship is by default, my linux server who receives every order from the trycorder, and execute it on the screen. So this way my server-screen shoot fire from the starship when you shoot fire on your trycorder.

This module who execute your functions on my display, is called the tryserver, and can be adapted to service any starship you own. 

You can change the server address in the settings, under the debug mode address, and try it on your server too. (provided you compiled the tryserver on your server too) available on github

Since the Trycorder is a Measuring and Communication device those functions will stay operationnal in any way, but i will add a MUTE-SERVER setting if you dont wish to receive alerts or comm links.

This should appear in 5.1.1 soon.
